name: GitHub Metrics

on:
  schedule:
    - cron: "21 5 * * *" # daily at 05:21 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: EclipseAditya
          template: classic
          base: header, repositories, metadata
          config_timezone: Asia/Kolkata
          filename: assets/github-metrics.svg
          # Plugins
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_ignored: html, css
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_followup: yes
